# This config is used for the debugger. More specifically the log level can be set with it.
version: 1
formatters:
  simple:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
loggers:
  "":
    level: DEBUG
    handlers: [ console ]
